FROM alpine:3.15.0
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN set -xe; \
    apk add --no-cache \
    libstdc++ \
    libgcc \
    git \
    nodejs \
    npm \
    ;

ARG NOALBS_VERSION=v1.9.5
RUN set -xe; \
    git clone https://github.com/715209/nginx-obs-automatic-low-bitrate-switching /app; \
    cd /app; \
    git checkout $NOALBS_VERSION; \
    npm install --production;

EXPOSE 5000/udp 8181/tcp 8282/udp

WORKDIR /app

ENTRYPOINT ["npm"]
CMD ["start"]